### ISSUE TITLE
TypeError: parseArgs is not a function

### ISSUE THREAD

**Issue by andrecasal** [brophdawg11/upgrade-remix#7]
Hey @brophdawg11. Was trying to upgrade remix and got this:

<img width="1020" alt="Screenshot 2023-12-21 at 12 00 32" src="https://github.com/brophdawg11/upgrade-remix/assets/22457463/843e5902-3a9b-487d-a91d-08dfd53dc65b">

Are you using something else and this package's deprecated?

**Comment by brophdawg11** [comment]
What version of node are you on?  This uses the built in node arg parser: https://nodejs.org/api/util.html#utilparseargsconfig

**Comment by brophdawg11** [comment]
Ah, I see 18.2 in the screenshot, and looks like that got added in 18.3 so you should just need to bump up to that or later.

I should bump the `engines` field in package.json to reflect 18.3 I suppose
